### ISSUE TITLE
MoneyType does not work

### ISSUE THREAD

**Issue by jblankendaal** [effektif/effektif#30]
When using a money-type, all kinds of weird things happen.

The variable is defined in bpmn as: 
```
      <e:variable id="Amount">
        <e:type name="money" />
      </e:variable>
```

The generated json in mongo looks like this:

        {
            "id" : "Amount",
            "type" : {
                "name" : "money",
                "javaClass" : "com.effektif.workflow.api.model.Money"
            }
        }

versus this for a normal variable (text in this case):

        {
            "id" : "Action",
            "type" : {
                "name" : "text"
            }
        }
I was able to assign a value to this money-type variable, but when sending a message() to a workflowInstance, I got the following error:
```
java.lang.RuntimeException: Couldn't cast 273 to a map
	at com.effektif.workflow.impl.json.types.AbstractBeanMapper.read(AbstractBeanMapper.java:53) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.JsonReader.readObject(JsonReader.java:33) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.types.VariableInstanceMapper.read(VariableInstanceMapper.java:51) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.types.VariableInstanceMapper.read(VariableInstanceMapper.java:28) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.JsonReader.readObject(JsonReader.java:33) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.JsonObjectMapper.read(JsonObjectMapper.java:55) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.json.JsonObjectMapper.read(JsonObjectMapper.java:47) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.mongo.MongoWorkflowInstanceStore.readVariableInstances(MongoWorkflowInstanceStore.java:571) ~[effektif-mongo-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.mongo.MongoWorkflowInstanceStore.readScopeImpl(MongoWorkflowInstanceStore.java:503) ~[effektif-mongo-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.mongo.MongoWorkflowInstanceStore.readWorkflowInstanceImpl(MongoWorkflowInstanceStore.java:491) ~[effektif-mongo-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.mongo.MongoWorkflowInstanceStore.findWorkflowInstances(MongoWorkflowInstanceStore.java:287) ~[effektif-mongo-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.mongo.MongoWorkflowInstanceStore.findWorkflowInstances(MongoWorkflowInstanceStore.java:279) ~[effektif-mongo-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.effektif.workflow.impl.WorkflowEngineImpl.findWorkflowInstances(WorkflowEngineImpl.java:226) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	at com.cumuluspro.effektif.Rest.message(Rest.java:143) ~[Rest.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.11.Final.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.23]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617) [catalina.jar:8.0.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.23]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.23]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-coyote.jar:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521) [tomcat-coyote.jar:8.0.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478) [tomcat-coyote.jar:8.0.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.23]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at com.effektif.workflow.impl.json.types.AbstractBeanMapper.read(AbstractBeanMapper.java:44) ~[effektif-workflow-impl-3.0.0-alpha3-SNAPSHOT.jar:na]
	... 48 common frames omitted
```

The 273 that could not be mapped was the actual value of the variableInstance...

**Comment by tombaeyens** [comment]
Hi Jeroen,

> The generated json in mongo looks like this:
> 
>     {
>         "id" : "Amount",
>         "type" : {
>             "name" : "money",
>             "javaClass" : "com.effektif.workflow.api.model.Money"
>         }
>     }

the javaClass should not be there.  it’s probably because `MoneyType extends JavaBeanType`.  we should find a solution for that.  don’t know the right one yet.

> java.lang.RuntimeException: Couldn't cast 273 to a map

values for money should be of type Money or in json, an object with an amount (number) and a currency (string)

-- Tom
