### ISSUE TITLE
MongoMemoryConfiguration does not seem to work

### ISSUE THREAD

**Issue by pfolthof** [effektif/effektif#9]
While doing some performance tests, we also tried to configure a hybrid configuration. The basic scenario below failed to run.

```java
public class Testcase {

    private static Configuration mongoConfiguration = new MongoConfiguration()
            .server("localhost")
            .databaseName("effektif");

    private static Configuration hybridConfiguration = new MongoMemoryConfiguration()
            .server("localhost")
            .databaseName("effektif");

    private static Configuration configuration = hybridConfiguration;

    private static WorkflowEngine engine = configuration.getWorkflowEngine();

    public static void main(String[] arguments) {

        Workflow workflow = new Workflow()
                .sourceWorkflowId("release")
                .variable("loadDecisionId", NumberType.INSTANCE)
                .activity("Decide where to go", new ExclusiveGateway()
                        .defaultTransitionId("To Quick Test")
                        .transitionWithConditionTo(new Equals()
                                .leftExpression("loadDecisionId")
                                .rightValue(1), "Perform Loadtest"))
                .transition(new Transition().id("To Quick Test").from("Decide where to go").to("Quick test"))
                .activity("Quick test", new UserTask())
                .activity("Perform Loadtest", new UserTask()
                        .transitionToNext())
                .activity("Notify community", new EmailTask()
                        .to("xxx@example.com")
                        .subject("New version released")
                        .bodyText("Enjoy!"));

        Deployment deployment = engine.deployWorkflow(workflow).checkNoErrorsAndNoWarnings();

        System.out.println("Deployed workflow " + deployment.getWorkflowId() + ", workflowId: " + workflow.getSourceWorkflowId());

        engine.start(new TriggerInstance().sourceWorkflowId(workflow.getSourceWorkflowId()));
    }
}
```

The relevant part of the stack trace is:

```
Exception in thread "main" java.lang.IllegalArgumentException: invalid ObjectId [fb5202f8-6e11-4e40-b44b-f92046dd72f4]
	at org.bson.types.ObjectId.<init>(ObjectId.java:181)
	at org.bson.types.ObjectId.<init>(ObjectId.java:167)
	at com.effektif.mongo.MongoHelper.writeIdOptNew(MongoHelper.java:51)
	at com.effektif.mongo.MongoWorkflowInstanceStore.writeWorkflowInstance(MongoWorkflowInstanceStore.java:379)
	at com.effektif.mongo.MongoWorkflowInstanceStore.insertWorkflowInstance(MongoWorkflowInstanceStore.java:141)
	at com.effektif.workflow.impl.WorkflowEngineImpl.startExecute(WorkflowEngineImpl.java:200)
	at com.effektif.workflow.impl.WorkflowEngineImpl.start(WorkflowEngineImpl.java:147)
	at com.effektif.workflow.impl.WorkflowEngineImpl.start(WorkflowEngineImpl.java:142)
```

Using the MongoConfiguration, we noticed that starting a large number of instances caused the performance of WorkflowEngine.start(InstanceTrigger) to degrade quickly (after about 10.000 entries). Maybe someone has an idea how to address this?

**Comment by tombaeyens** [comment]
@pfolthof can you check if my fix works for you?  i pushed it to master.  Please close this issue if this fixed the problem for you.

As for the performance, it might be some index missing.  Can you see which query is getting slow.  (i suspect a query, rather then an insert getting slow)

**Comment by pfolthof** [comment]
Hi Tom,

Sorry, but your fix did not help. The new stack trace is:

```
Exception in thread "main" java.lang.IllegalArgumentException: invalid ObjectId [4bfb6d4b-e3a1-4b6f-ab10-5712c20f8102]
	at org.bson.types.ObjectId.<init>(ObjectId.java:181)
	at org.bson.types.ObjectId.<init>(ObjectId.java:167)
	at com.effektif.mongo.MongoHelper.writeIdOptNew(MongoHelper.java:51)
	at com.effektif.mongo.MongoTaskStore.taskToMongo(MongoTaskStore.java:178)
	at com.effektif.mongo.MongoTaskStore.insertTask(MongoTaskStore.java:91)
	at com.effektif.workflow.impl.activity.types.UserTaskImpl.execute(UserTaskImpl.java:165)
	at com.effektif.workflow.impl.workflowinstance.ActivityInstanceImpl.execute(ActivityInstanceImpl.java:84)
	at com.effektif.workflow.impl.workflowinstance.WorkflowInstanceImpl.executeWork(WorkflowInstanceImpl.java:148)
	at com.effektif.workflow.impl.WorkflowEngineImpl.startExecute(WorkflowEngineImpl.java:201)
	at com.effektif.workflow.impl.WorkflowEngineImpl.start(WorkflowEngineImpl.java:147)
	at com.effektif.workflow.impl.WorkflowEngineImpl.start(WorkflowEngineImpl.java:142)
```

The slowest queries in MongoDB seem to be:

```
> db.system.profile.find({$query: {}, $orderby:{millis:-1}})
```

```json
{ "op" : "update", "ns" : "effektif.workflowInstances", "query" : { "id" : ObjectId("552fc955e4b04b647fb8bd27") }, "updateobj" : { "$set" : { "activities" : [ { "id" : "2", "activityId" : "Quick test", "workState" : "waiting", "start" : ISODate("2015-04-16T14:38:13.570Z") } ] }, "$unset" : { "lock" : 1 } }, "nscanned" : 0, "nscannedObjects" : 136732, "nMatched" : 1, "nModified" : 1, "keyUpdates" : 0, "writeConflicts" : 0, "numYield" : 1068, "locks" : {  }, "millis" : 439, "execStats" : {  }, "ts" : ISODate("2015-04-16T14:38:14.010Z"), "client" : "127.0.0.1", "allUsers" : [ ], "user" : "" }
{ "op" : "insert", "ns" : "effektif.workflows", "query" : { "_id" : ObjectId("552fc94be4b04b647fb8b5b1"), "activities" : [ { "type" : "exclusiveGateway", "id" : "Decide where to go", "defaultTransitionId" : "To Quick Test" }, { "type" : "userTask", "id" : "Quick test" }, { "type" : "userTask", "id" : "Perform Loadtest" }, { "type" : "email", "id" : "Notify community", "toEmailAddresses" : [ { "value" : "xxx@example.com" } ], "subject" : "New version released", "bodyText" : "Enjoy!" } ], "transitions" : [ { "id" : "To Quick Test", "from" : "Decide where to go", "to" : "Quick test" }, { "from" : "Decide where to go", "to" : "Perform Loadtest", "condition" : { "type" : "equals", "left" : { "expression" : "loadDecisionId" }, "right" : { "value" : 1 } } }, { "from" : "Perform Loadtest", "to" : "Notify community" } ], "variables" : [ { "id" : "loadDecisionId", "type" : { "name" : "number" } } ], "sourceWorkflowId" : "release3289", "createTime" : "2015-04-16T14:38:03.667", "deployedTime" : ISODate("2015-04-16T14:38:03.667Z") }, "ninserted" : 1, "keyUpdates" : 0, "writeConflicts" : 0, "numYield" : 0, "locks" : { "Global" : { "acquireCount" : { "w" : NumberLong(1) } }, "MMAPV1Journal" : { "acquireCount" : { "w" : NumberLong(2) }, "acquireWaitCount" : { "w" : NumberLong(1) }, "timeAcquiringMicros" : { "w" : NumberLong(383223) } }, "Database" : { "acquireCount" : { "w" : NumberLong(1) } }, "Collection" : { "acquireCount" : { "W" : NumberLong(1) } } }, "millis" : 383, "execStats" : {  }, "ts" : ISODate("2015-04-16T14:38:04.051Z"), "client" : "127.0.0.1", "allUsers" : [ ], "user" : "" }
{ "op" : "update", "ns" : "effektif.workflowInstances", "query" : { "id" : ObjectId("552fc958e4b04b647fb8bd63") }, "updateobj" : { "$set" : { "activities" : [ { "id" : "2", "activityId" : "Quick test", "workState" : "waiting", "start" : ISODate("2015-04-16T14:38:16.325Z") } ] }, "$unset" : { "lock" : 1 } }, "nscanned" : 0, "nscannedObjects" : 136752, "nMatched" : 1, "nModified" : 1, "keyUpdates" : 0, "writeConflicts" : 0, "numYield" : 1068, "locks" : {  }, "millis" : 227, "execStats" : {  }, "ts" : ISODate("2015-04-16T14:38:16.553Z"), "client" : "127.0.0.1", "allUsers" : [ ], "user" : "" }
{ "op" : "update", "ns" : "effektif.workflowInstances", "query" : { "id" : ObjectId("552fc951e4b04b647fb8bcc7") }, "updateobj" : { "$set" : { "activities" : [ { "id" : "2", "activityId" : "Quick test", "workState" : "waiting", "start" : ISODate("2015-04-16T14:38:09.627Z") } ] }, "$unset" : { "lock" : 1 } }, "nscanned" : 0, "nscannedObjects" : 136700, "nMatched" : 1, "nModified" : 1, "keyUpdates" : 0, "writeConflicts" : 0, "numYield" : 1067, "locks" : {  }, "millis" : 194, "execStats" : {  }, "ts" : ISODate("2015-04-16T14:38:09.822Z"), "client" : "127.0.0.1", "allUsers" : [ ], "user" : "" }
```

**Comment by pfolthof** [comment]
As far as I can determine, the index is on _id and not on id.

**Comment by pfolthof** [comment]
It looks like there is a typo in MongoWorkflowInstanceStore.java. In interface ScopeInstanceFields, String _ID = "id" should be "_id".

**Comment by tombaeyens** [comment]
Thanks! I'll fix it one of the next days

**Comment by tombaeyens** [comment]
fyi 
The workflow instance id field name is `_id`
The activity instance id field name is `id`
Thanks for finding and reporting this
